defaults: &defaults
  working_directory: /tmp/repo
  docker:
    # specify the version you desire here
    - image: circleci/node:8.12.0-browsers

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # build TypeScript
          name: build typescript
          command: npm run build

  ut:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/
      - run: # run tests
          name: test
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - ut:
          requires:
            - build
          filters:
            branches:
              only: master